# Generated by Django 4.2.28 on 2026-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(blank=True, help_text='Criteria for marking this assignment', null=True),
        ),
    ]
