# Generated by Django 4.2.28 on 2026-02-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_assignment_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('skills_extracted', models.JSONField(blank=True, help_text='Extracted skills from resume', null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FLAGGED', 'Flagged for Review')], default='IN_PROGRESS', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='proctoring_videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='proctoring_audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('integrity_score', models.FloatField(blank=True, help_text='Score from 0-10 indicating exam integrity', null=True)),
                ('flagged_issues', models.JSONField(blank=True, help_text='List of potential issues detected', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_audio', models.FileField(blank=True, null=True, upload_to='responses_audio/')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('ai_evaluation', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.proctoringquestion')),
            ],
        ),
        migrations.AddField(
            model_name='proctoringquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.proctoringsession'),
        ),
    ]
